name: Deploy Airflow Project

on:
  push:
    branches:
      - Main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy DAGs to Airflow Project
        shell: powershell
        run: |
          $source = "$env:GITHUB_WORKSPACE\dags"
          $destination = "C:\airflow_project\dags"

          if (!(Test-Path $destination)) {
              New-Item -ItemType Directory -Path $destination
          }

          Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
